name: Terraform Destroy

on:
  workflow_dispatch:  # Only runs manually from GitHub UI

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        working-directory: labs/02-terraform-ec2-docker
        run: terraform init -input=false

      - name: Terraform Destroy Preview
        working-directory: labs/02-terraform-ec2-docker
        run: terraform plan -destroy

      - name: Terraform Destroy
        working-directory: labs/02-terraform-ec2-docker
        run: terraform destroy -auto-approve
