name: Terraform CI

on:
  pull_request:
    paths:
      - 'labs/02-terraform-ec2-docker/**'

jobs:
  lint-workflows:
    name: Lint workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint workflow files
        uses: rhysd/actionlint@v1

  fmt:
    name: Lint, Init & Validate
    runs-on: ubuntu-latest
    needs: lint-workflows
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform fmt check
        working-directory: labs/02-terraform-ec2-docker
        run: terraform fmt -check

      - name: Terraform init (with backend)
        working-directory: labs/02-terraform-ec2-docker
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: labs/02-terraform-ec2-docker
        run: terraform validate

  plan:
    name: Plan
    needs: fmt
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform init & plan
        working-directory: labs/02-terraform-ec2-docker
        run: |
          terraform init -input=false
          terraform plan -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: labs/02-terraform-ec2-docker/tfplan
